説明を追加、権限に関する脆弱性を修正など
RT-Team/rt-bot pull request #187
Opened 2022-01-03 14:47 UTC by yaakiyu

・コマンドにextra・documentをつけた。
・辞書のキーはstrにしておいた。(バグが起きる可能性があるため)
・メンバーをキックする権限がないとコマンドが発動しないようにした。
・設定に成功したときにEmbedを送信するようにした。

2022-01-03 22:43 UTC, tasuren requested changes
三つ変更して欲しい箇所がある。

2022-01-03 22:43 UTC, tasuren commented on cogs/rta.py
>          async def self.db.get_cursor() as c:
このdefをwithに変えて欲しい。

2022-01-03 22:43 UTC, tasuren commented on cogs/rta.py
> +                    embed = discord.Embed(title = "即抜けRTA", description = f"{member}が{round(time() - self.users[member.id], 6)}秒で抜けちゃった。。。")
キーをなぜやったのか分からないが文字列に変えてるので、ここで文字列にしていないから`KeyError`が起きてしまう。

2022-01-03 22:43 UTC, tasuren commented on cogs/rta.py
> +            member.id
これを消して欲しい。

2022-01-04 01:02 UTC, yaakiyu commented on cogs/rta.py
>          async def self.db.get_cursor() as c:
このdefはDMS君のせいですねぇ(気付かなかったが)

2022-01-04 01:10 UTC, tasuren requested changes
一ヶ所

2022-01-04 01:10 UTC, tasuren commented on cogs/rta.py
> +            self.users.remove(str(member.id))
辞書に`remove`はない。

2022-01-04 01:15 UTC, tasuren requested changes
三ヶ所

2022-01-04 01:15 UTC, tasuren commented on cogs/rta.py
>                  channel = await self.db.get_channel()
引数が足りない。

2022-01-04 01:15 UTC, tasuren commented on cogs/rta.py
>              return self.bot.get_channel(int(data[1]))
無駄なintを消して欲しい。

2022-01-04 01:15 UTC, tasuren commented on cogs/rta.py
> +        self.users[str(member.id)] = time()
メモリリークする。
`tasks`か何かで定期的に古いものは消すようにして欲しい。

2022-01-04 02:03 UTC, tasuren approved these changes
Good job

2022-01-04 02:03 UTC, merged