update: RTの複雑な環境について少し解説を追加した
RT-Team/rt-bot pull request #219
Opened 2022-02-01 13:29 UTC by yaakiyu

間違えて途中でアルファベットにしたまま入力してenter押したせいで途中で変な風に終わってるけど。

2022-02-01 21:29 UTC, tasuren requested changes
二箇所変更を要求

2022-02-01 21:29 UTC, tasuren commented on contributing.md
> +commands.commandの引数にheaddingやparentをつけることができます。
`extras`に辞書で入れて欲しい。
`parent`は被っちゃってた。

2022-02-01 21:29 UTC, tasuren commented on contributing.md
> +Context.sendのcontent引数に{"ja":"...", "en":"..."}の形式で辞書を入れると、
全てが対応済みに変えて欲しい。

2022-02-02 03:55 UTC, yaakiyu commented
修正。

2022-02-02 04:03 UTC, tasuren approved these changes
Nice

2022-02-02 04:03 UTC, merged