change : 他人の情報見れる要素作った
RT-Team/rt-bot pull request #241
Opened 2022-02-22 13:36 UTC by Nemu627

levelコマンドのパラメーター増やしただけ

2022-02-22 21:45 UTC, tasuren requested changes
ヘルプにそのことを追記して欲しい。

2022-02-23 08:28 UTC, tasuren requested changes
> RTのいるユーザーしかユーザー指定はできません。

`RTがいるサーバーにいるユーザーのみ指定可能です。`にして欲しい。  
それと英語ヘルプも書いて欲しい。(自力じゃなくてDeepL翻訳使えばいい。)

2022-02-23 08:31 UTC, Nemu627 commented
修正済み。
近々国語のテストがあるのですが、心配です。TwT

2022-02-23 08:32 UTC, tasuren requested changes
すまん、英語ヘルプも書いて欲しい。(自力じゃなくてDeepL翻訳使えばいい。)

2022-02-23 08:37 UTC, Nemu627 commented
追加。
やろうとして忘れちゃうことってよくあることだと思うんです(言い訳)

2022-02-23 08:45 UTC, tasuren approved these changes
Okay

2022-02-23 08:45 UTC, merged