ログ機能に編集を追加
RT-Team/rt-bot pull request #269
Opened 2022-03-10 15:16 UTC by tuna2134

2022-03-10 21:09 UTC, tasuren requested changes
`getattr`の第三引数にデフォルト値として`""`を渡して欲しい。

2022-03-10 22:49 UTC, tuna2134 commented
やっといた

2022-03-10 22:49 UTC, tuna2134 commented
やっといた

2022-03-11 07:44 UTC, tasuren approved these changes
Okay

2022-03-11 07:44 UTC, merged