投票rt追加
RT-Team/rt-bot pull request #270
Opened 2022-03-10 15:21 UTC by tuna2134

2022-03-10 21:06 UTC, tasuren requested changes
`rt!`だけじゃなくて`rt!poll`じゃないと動かないと思う。

2022-03-10 22:44 UTC, tuna2134 commented
あ
了解

2022-03-10 22:45 UTC, tuna2134 commented
編集した

2022-03-11 04:24 UTC, yaakiyu requested changes
bot.process_command() ではなく
bot.process_commands()
sが必要。

2022-03-11 04:44 UTC, tuna2134 commented
しゅうせいした

2022-03-11 04:44 UTC, tuna2134 commented
しゅうせいした

2022-03-11 04:54 UTC, tasuren approved these changes
Okay

2022-03-11 13:06 UTC, yaakiyu commented
間違えた、requestしてしまった
実はreviewするの初めてで()

2022-03-11 13:06 UTC, yaakiyu approved these changes

2022-03-11 13:09 UTC, tasuren commented
> 実はreviewするの初めてで()

処評がなくなったね。

2022-03-11 13:09 UTC, merged