暇だからメッセージ編集できるようにした
RT-Team/rt-bot pull request #271
Opened 2022-03-10 15:25 UTC by tuna2134

2022-03-10 21:07 UTC, tasuren requested changes
そこ実行されなくない？
あとなんのためのやつなの？

2022-03-10 22:46 UTC, tuna2134 commented
m = await ctx.reply("testing")
await m.edit(content="test")

2022-03-10 22:46 UTC, tuna2134 commented
こんな感じに作れるようにしようと思ったんだが

2022-03-11 04:29 UTC, yaakiyu commented
元からreplyの引数にreply_editあるくね
あとoriginal_messageって送信したメッセージじゃなくって返信先のメッセージ...?

2022-03-11 04:45 UTC, tuna2134 commented
interaction.response.send_messageで送信したメッセージを取得するやつ

2022-03-11 04:53 UTC, tasuren approved these changes
I see

2022-03-11 04:53 UTC, merged