500エラーを特定のチャンネルに送信するようにした
RT-Team/rt-bot pull request #282
Opened 2022-03-24 09:44 UTC by tuna2134

2022-03-24 09:55 UTC, tasuren requested changes
定期的にまとめて送信するようにしてほしい。

2022-03-24 10:01 UTC, tuna2134 commented
ページ形式にしていい？

2022-03-24 10:02 UTC, tuna2134 commented
もしくはembedsで送信

2022-03-24 10:07 UTC, tasuren commented
なんだったらファイルでもいい

2022-03-24 10:08 UTC, tuna2134 commented
Oh…

2022-03-24 10:08 UTC, tuna2134 commented
ファイルにするわ

2022-03-24 10:09 UTC, tuna2134 commented
どんな形式にする？

2022-03-24 10:09 UTC, tuna2134 commented
テキストファイル？

2022-03-24 10:09 UTC, tuna2134 commented
コマンド
エラー内容
って感じ？

2022-03-24 10:09 UTC, tasuren commented
ログみたいな感じでも見安けりゃなんでも良い。
もしファイル保存してからアップロードするなら`data`フォルダに保存してね。

2022-03-24 10:11 UTC, tuna2134 commented
りょうかーい

2022-03-27 12:48 UTC, tuna2134 commented
@tasuren やったよお

2022-03-28 01:04 UTC, closed without merging