エラー関連の改善・ログ作成
RT-Team/rt-bot pull request #283
Opened 2022-03-27 01:16 UTC by yaakiyu

DMSがPR出してたけどなんか終わる気がしないので。

2022-03-27 01:33 UTC, tasuren requested changes
2箇所コメントと変更要求

2022-03-27 01:33 UTC, tasuren commented on cogs/bot_general.py
> +        error_logs = set(self.errors)
なんでここで集合に変換しているの？

2022-03-27 01:33 UTC, tasuren commented on cogs/bot_general.py
> +            file=StringIO("\n\n".join(error_logs))
`discord.File`じゃないとダメだったはず。

2022-03-27 02:45 UTC, yaakiyu commented on cogs/bot_general.py
> +        error_logs = set(self.errors)
見やすくするために重複するエラーを省いてる。

2022-03-27 02:55 UTC, yaakiyu commented on cogs/bot_general.py
> +            file=StringIO("\n\n".join(error_logs))
修正。

2022-03-27 05:06 UTC, tasuren commented on cogs/bot_general.py
> +        error_logs = set(self.errors)
最初から集合にして欲しい。

2022-03-27 05:07 UTC, tasuren requested changes
一箇所コメントの返信にて変更を要求

2022-03-27 06:56 UTC, yaakiyu commented on cogs/bot_general.py
> +        error_logs = set(self.errors)
ok

2022-03-27 07:27 UTC, tasuren requested changes
変更を要求

2022-03-27 07:27 UTC, tasuren commented on cogs/bot_general.py
> +        self.errors = []
最初から集合ってのはここを集合にして欲しいってことね。

2022-03-27 07:36 UTC, yaakiyu commented on cogs/bot_general.py
> +        self.errors = []
集合って変更不可じゃなかったっけ?

2022-03-27 07:43 UTC, tasuren commented on cogs/bot_general.py
> +        self.errors = []
`add`がある。

2022-03-27 12:49 UTC, tuna2134 commented
一週間も経っていないのに。。。

2022-03-27 12:49 UTC, tuna2134 commented
用事というものを考えないのかね？

2022-03-27 13:18 UTC, tasuren commented
あ、まじか
だいぶ前かと思ってた。
スマソ

2022-03-27 22:18 UTC, tasuren commented
あ、まじか
だいぶ前かと思ってた。
スマソ

2022-03-28 00:13 UTC, yaakiyu commented
僕はちょい前に豆知識コーナーで頑張る宣言しちゃったからやってたんだけどな
一応直したけどこっち閉じる?

2022-03-28 01:00 UTC, tasuren commented
いや今回はこっちマージする。

2022-03-28 01:00 UTC, tasuren approved these changes
Okay

2022-03-28 01:00 UTC, merged